# Generated by Django 4.2 on 2023-07-04 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_category_alter_article_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('1', 'Красота'), ('2', 'Мода')], default='Мода', max_length=10),
        ),
    ]
