# Generated by Django 4.2 on 2023-07-04 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('surname', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('city', models.CharField(max_length=150, verbose_name='Город')),
                ('profile_pic', models.ImageField(blank=True, default='default_user_pic.jpg', upload_to='', verbose_name='Изображение')),
                ('about', models.TextField(verbose_name='О себе')),
            ],
        ),
    ]
